# Generated by Django 6.0.3 on 2026-03-08 18:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "runtime",
                    models.CharField(
                        choices=[("modal", "Modal"), ("docker", "Docker")],
                        max_length=20,
                    ),
                ),
                ("sandbox_id", models.CharField(blank=True, max_length=255)),
                ("vnc_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("deploying", "Deploying"),
                            ("running", "Running"),
                            ("waiting", "Waiting"),
                            ("idle", "Idle"),
                            ("stopped", "Stopped"),
                            ("error", "Error"),
                        ],
                        default="deploying",
                        max_length=20,
                    ),
                ),
                ("team_name", models.CharField(blank=True, max_length=100)),
                ("parent_session_id", models.CharField(blank=True, max_length=255)),
                ("session_id", models.CharField(blank=True, max_length=255)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("permission_mode", models.CharField(blank=True, max_length=30)),
                ("allowed_tools", models.JSONField(blank=True, default=list)),
                ("mcp_servers", models.JSONField(blank=True, default=dict)),
                ("workspace_path", models.CharField(blank=True, max_length=500)),
                ("volume_mounts", models.JSONField(blank=True, default=list)),
                ("instructions", models.TextField(blank=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("lead", "Lead"), ("worker", "Worker")],
                        default="worker",
                        max_length=10,
                    ),
                ),
                ("config_snapshot", models.JSONField(blank=True, default=dict)),
                ("agent_type", models.CharField(default="claude-code", max_length=50)),
                ("latest_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "session_cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("capabilities", models.JSONField(blank=True, null=True)),
                ("phase", models.CharField(blank=True, default="", max_length=20)),
                ("mode", models.CharField(default="auto", max_length=20)),
                ("attention_level", models.CharField(default="none", max_length=20)),
                ("task", models.CharField(blank=True, default="", max_length=500)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "relay_token",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("relay_connected", models.BooleanField(default=False)),
                ("relay_disconnected_at", models.DateTimeField(blank=True, null=True)),
                ("triggers", models.JSONField(blank=True, default=list)),
                ("compute_seconds", models.BigIntegerField(default=0)),
                ("deployed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("session_id", models.CharField(blank=True, max_length=255)),
                ("rating", models.IntegerField()),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="agents.agent",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(default="pending", max_length=32)),
                ("assignee", models.CharField(blank=True, max_length=255)),
                ("active_form", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("blocks", models.JSONField(blank=True, default=list)),
                ("blocked_by", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="agents.agent",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectSecret",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("encrypted_value", models.BinaryField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secrets",
                        to="projects.project",
                    ),
                ),
                (
                    "scoped_agents",
                    models.ManyToManyField(
                        blank=True, related_name="scoped_secrets", to="agents.agent"
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="SessionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100)),
                ("is_error", models.BooleanField(default=False)),
                (
                    "total_cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("duration_ms", models.IntegerField(default=0)),
                ("duration_api_ms", models.IntegerField(default=0)),
                ("num_turns", models.IntegerField(default=0)),
                ("model_usage", models.JSONField(default=dict)),
                ("permission_denials", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_results",
                        to="agents.agent",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("content", models.TextField()),
                ("assigned_tags", models.JSONField(default=list)),
                ("assigned_to_all", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StreamEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=100)),
                ("event_type", models.CharField(max_length=50)),
                (
                    "message_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("data", models.JSONField(default=dict)),
                ("is_canonical", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stream_events",
                        to="agents.agent",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeamFeedItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("user", "User"),
                            ("summary", "Summary"),
                            ("status", "Status"),
                            ("error", "Error"),
                            ("question", "Question"),
                            ("plan", "Plan"),
                            ("permission", "Permission"),
                            ("multi-question", "Multi Question"),
                            ("agent-message", "Agent Message"),
                            ("task", "Task"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "agent_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("text", models.TextField(blank=True, default="")),
                ("command", models.TextField(blank=True, default="")),
                ("risk", models.CharField(blank=True, default="", max_length=200)),
                (
                    "perm_status",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "tool_use_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("title", models.CharField(blank=True, default="", max_length=500)),
                ("plan", models.TextField(blank=True, default="")),
                (
                    "plan_status",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("summary", models.TextField(blank=True, default="")),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                ("turns", models.IntegerField(blank=True, null=True)),
                ("duration", models.CharField(blank=True, default="", max_length=30)),
                ("is_error", models.BooleanField(blank=True, null=True)),
                (
                    "from_value",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("to_value", models.CharField(blank=True, default="", max_length=100)),
                ("target", models.CharField(blank=True, default="", max_length=100)),
                ("question", models.CharField(blank=True, default="", max_length=1000)),
                ("options", models.JSONField(blank=True, default=list)),
                ("questions", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feed_items",
                        to="agents.agent",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_items",
                        to="projects.project",
                    ),
                ),
                (
                    "source_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="agents.streamevent",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="agent",
            constraint=models.UniqueConstraint(
                fields=("project", "name"), name="unique_project_agent_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="agenttask",
            constraint=models.UniqueConstraint(
                fields=("project", "task_id"), name="unique_project_task_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectsecret",
            constraint=models.UniqueConstraint(
                fields=("project", "key"), name="unique_project_secret_key"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionresult",
            index=models.Index(
                fields=["agent", "created_at"], name="agents_sess_agent_i_b7925c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="skill",
            constraint=models.UniqueConstraint(
                fields=("project", "name"), name="unique_project_skill"
            ),
        ),
        migrations.AddIndex(
            model_name="streamevent",
            index=models.Index(
                fields=["agent", "created_at"], name="agents_stre_agent_i_3fac22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="streamevent",
            index=models.Index(
                fields=["agent", "session_id", "created_at"],
                name="agents_stre_agent_i_5e970d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teamfeeditem",
            index=models.Index(
                fields=["project", "created_at"], name="agents_team_project_296fd3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamfeeditem",
            index=models.Index(
                fields=["project", "agent_name", "type", "perm_status"],
                name="agents_team_project_e7fd6f_idx",
            ),
        ),
    ]
