# Generated by Codex on 2026-03-08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentLifecycleAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("create", "Create"), ("restart", "Restart")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("step", models.CharField(default="queued", max_length=64)),
                ("attempt_no", models.PositiveIntegerField(default=1)),
                ("correlation_id", models.CharField(blank=True, default="", max_length=64)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("error_detail", models.TextField(blank=True, default="")),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lifecycle_attempts",
                        to="agents.agent",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="agentlifecycleattempt",
            index=models.Index(
                fields=["agent", "status", "started_at"],
                name="agents_agen_agent_id_8f96af_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agentlifecycleattempt",
            index=models.Index(
                fields=["correlation_id"],
                name="agents_agen_correla_736f80_idx",
            ),
        ),
    ]
