# Generated by Django 6.0.2 on 2026-02-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='status',
            field=models.CharField(choices=[('deploying', 'Deploying'), ('working', 'Working'), ('conversing', 'Conversing'), ('needs_info', 'Needs Info'), ('blocked', 'Blocked'), ('completed', 'Completed'), ('goal_changed', 'Goal Changed'), ('dead', 'Dead')], default='deploying', max_length=20),
        ),
    ]
