# Generated by Django 6.0.3 on 2026-03-09 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_agentlifecycleattempt"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="agentlifecycleattempt",
            new_name="agents_agen_agent_i_7fe3ac_idx",
            old_name="agents_agen_agent_id_8f96af_idx",
        ),
        migrations.RenameIndex(
            model_name="agentlifecycleattempt",
            new_name="agents_agen_correla_640258_idx",
            old_name="agents_agen_correla_736f80_idx",
        ),
    ]
