# Generated by Django 6.0.2 on 2026-02-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_alter_agent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='status',
            field=models.CharField(choices=[('deploying', 'Deploying'), ('working', 'Working'), ('conversing', 'Conversing'), ('needs_info', 'Needs Info'), ('blocked', 'Blocked'), ('completed', 'Completed'), ('goal_changed', 'Goal Changed'), ('dead', 'Dead'), ('terminated', 'Terminated')], default='deploying', max_length=20),
        ),
    ]
