# Generated by Django 6.0.2 on 2026-02-07 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_add_terminated_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agent',
            name='unique_agent_per_project',
        ),
    ]
