# Generated by Django 6.0.3 on 2026-03-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0004_accountsecret"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="desired_status",
            field=models.CharField(
                choices=[("deployed", "Deployed"), ("stopped", "Stopped")],
                default="deployed",
                max_length=20,
            ),
        ),
    ]
