# Generated by Django 6.0.2 on 2026-02-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0004_remove_unique_agent_name_constraint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agentusage",
            name="agent",
        ),
        migrations.RemoveIndex(
            model_name="case",
            name="case_embedding_idx",
        ),
        migrations.DeleteModel(
            name="Case",
        ),
        migrations.RemoveField(
            model_name="goal",
            name="project",
        ),
        migrations.RemoveField(
            model_name="goaltrajectory",
            name="goal",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="goal",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="completed_at",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="confidence",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="output",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="reasoning",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="sentiment",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="summary",
        ),
        migrations.AddField(
            model_name="agent",
            name="parent_session_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="agent",
            name="session_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="agent",
            name="team_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="agent",
            name="status",
            field=models.CharField(
                choices=[
                    ("deploying", "Deploying"),
                    ("running", "Running"),
                    ("stopped", "Stopped"),
                    ("error", "Error"),
                ],
                default="deploying",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="AgentUsage",
        ),
        migrations.DeleteModel(
            name="GoalTrajectory",
        ),
        migrations.DeleteModel(
            name="Goal",
        ),
    ]
