# Generated by Django 6.0.2 on 2026-02-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0005_remove_agentusage_agent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="cwd",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="agent",
            name="model",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="agent",
            name="permission_mode",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="agent",
            name="transcript_path",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
