# Generated by Django 6.0.2 on 2026-02-08 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0006_agent_cwd_agent_model_agent_permission_mode_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AgentEvent",
        ),
    ]
