# Generated by Django 6.0.3 on 2026-03-21 02:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0007_agent_runtime_status_projection"),
        ("projects", "0003_project_theme_document"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IncidentCapture",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("screenshot_url", models.URLField(blank=True, default="")),
                ("window_minutes", models.IntegerField(default=30)),
                ("bundle", models.JSONField(default=dict)),
                ("collection_errors", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="incidentcapture",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incidents",
                to="agents.agent",
            ),
        ),
        migrations.AddField(
            model_name="incidentcapture",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incidents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="incidentcapture",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incidents",
                to="projects.project",
            ),
        ),
        migrations.AddIndex(
            model_name="incidentcapture",
            index=models.Index(
                fields=["project", "created_at"], name="agents_inci_project_de0616_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incidentcapture",
            index=models.Index(
                fields=["agent", "created_at"], name="agents_inci_agent_i_e04daa_idx"
            ),
        ),
    ]
