# Generated by Django 6.0.2 on 2026-02-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0007_delete_agentevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="status",
            field=models.CharField(
                choices=[
                    ("deploying", "Deploying"),
                    ("running", "Running"),
                    ("idle", "Idle"),
                    ("stopped", "Stopped"),
                    ("error", "Error"),
                ],
                default="deploying",
                max_length=20,
            ),
        ),
    ]
