# Generated by Django 6.0.3 on 2026-03-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0008_incident_capture"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="task_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="last_execution_event_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
