# Generated by Django 6.0.2 on 2026-02-08 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0008_alter_agent_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="mcp_servers",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="AgentMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="agents.agent",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
