# Generated by Django 6.0.3 on 2026-03-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0009_add_task_timestamps"),
    ]

    operations = [
        migrations.AddField(
            model_name="streamevent",
            name="task_id",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
