# Generated by Django 6.0.3 on 2026-04-03 17:27

from django.db import migrations


def _rename_index_if_needed(schema_editor, *, old_name: str, new_name: str) -> None:
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT 1 FROM pg_class WHERE relkind = 'i' AND relname = %s",
            [old_name],
        )
        old_exists = cursor.fetchone() is not None
        cursor.execute(
            "SELECT 1 FROM pg_class WHERE relkind = 'i' AND relname = %s",
            [new_name],
        )
        new_exists = cursor.fetchone() is not None
        if old_exists and not new_exists:
            cursor.execute(f"ALTER INDEX {old_name} RENAME TO {new_name}")


def _rename_agent_started_index_forward(apps, schema_editor):
    _rename_index_if_needed(
        schema_editor,
        old_name="agents_runt_agent_i_42ec2e_idx",
        new_name="agents_runt_agent_i_6fae46_idx",
    )


def _rename_agent_started_index_backward(apps, schema_editor):
    _rename_index_if_needed(
        schema_editor,
        old_name="agents_runt_agent_i_6fae46_idx",
        new_name="agents_runt_agent_i_42ec2e_idx",
    )


def _rename_project_started_index_forward(apps, schema_editor):
    _rename_index_if_needed(
        schema_editor,
        old_name="agents_runt_project_6b32e2_idx",
        new_name="agents_runt_project_6b1f38_idx",
    )


def _rename_project_started_index_backward(apps, schema_editor):
    _rename_index_if_needed(
        schema_editor,
        old_name="agents_runt_project_6b1f38_idx",
        new_name="agents_runt_project_6b32e2_idx",
    )


def _rename_provider_started_index_forward(apps, schema_editor):
    _rename_index_if_needed(
        schema_editor,
        old_name="agents_runt_provider_339550_idx",
        new_name="agents_runt_provide_b8aedb_idx",
    )


def _rename_provider_started_index_backward(apps, schema_editor):
    _rename_index_if_needed(
        schema_editor,
        old_name="agents_runt_provide_b8aedb_idx",
        new_name="agents_runt_provider_339550_idx",
    )


def _rename_sandbox_index_forward(apps, schema_editor):
    _rename_index_if_needed(
        schema_editor,
        old_name="agents_runt_sandbox_3fda64_idx",
        new_name="agents_runt_sandbox_130fd2_idx",
    )


def _rename_sandbox_index_backward(apps, schema_editor):
    _rename_index_if_needed(
        schema_editor,
        old_name="agents_runt_sandbox_130fd2_idx",
        new_name="agents_runt_sandbox_3fda64_idx",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0011_incident_capture_set_null_fks"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    _rename_agent_started_index_forward,
                    _rename_agent_started_index_backward,
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="runtimesegment",
                    new_name="agents_runt_agent_i_6fae46_idx",
                    old_name="agents_runt_agent_i_42ec2e_idx",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    _rename_project_started_index_forward,
                    _rename_project_started_index_backward,
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="runtimesegment",
                    new_name="agents_runt_project_6b1f38_idx",
                    old_name="agents_runt_project_6b32e2_idx",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    _rename_provider_started_index_forward,
                    _rename_provider_started_index_backward,
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="runtimesegment",
                    new_name="agents_runt_provide_b8aedb_idx",
                    old_name="agents_runt_provider_339550_idx",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    _rename_sandbox_index_forward,
                    _rename_sandbox_index_backward,
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="runtimesegment",
                    new_name="agents_runt_sandbox_130fd2_idx",
                    old_name="agents_runt_sandbox_3fda64_idx",
                ),
            ],
        ),
    ]
