# Generated by Django 6.0.2 on 2026-02-09 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0014_stream_json_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='agents_mess_agent_i_44149d_idx',
            old_name='agents_mess_agent_i_idx',
        ),
    ]
