# Generated by Django 6.0.2 on 2026-02-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0016_secretgroup_agent_secret_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='config_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('lead', 'Lead'), ('worker', 'Worker')], default='worker', max_length=10),
        ),
    ]
