# Generated by Django 6.0.2 on 2026-02-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0018_agentevent_summary'),
        ('projects', '0002_remove_project_anthropic_api_key_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_project_agent_name'),
        ),
    ]
