# Generated by Django 6.0.2 on 2026-02-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0020_drop_unique_session_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='pending_inbox',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
