# Generated by Django 6.0.2 on 2026-02-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0021_add_pending_inbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='volume_mounts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
