# Generated by Django 6.0.2 on 2026-02-15 01:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0022_add_volume_mounts'),
        ('projects', '0002_remove_project_anthropic_api_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSecret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('encrypted_value', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='projects.project')),
                ('scoped_agents', models.ManyToManyField(blank=True, related_name='scoped_secrets', to='agents.agent')),
            ],
            options={
                'ordering': ['key'],
                'constraints': [models.UniqueConstraint(fields=('project', 'key'), name='unique_project_secret_key')],
            },
        ),
    ]
