# Generated by Django 6.0.2 on 2026-02-15 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0023_projectsecret'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='secretgroup',
            name='unique_project_secret_group',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='secret_groups',
        ),
        migrations.DeleteModel(
            name='SecretGroup',
        ),
    ]
