# Generated by Django 6.0.2 on 2026-02-19 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0025_agent_task_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentfeedback',
            name='message',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='pending_inbox',
        ),
        migrations.DeleteModel(
            name='AgentMessage',
        ),
    ]
