# Generated by Django 6.0.2 on 2026-02-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0026_drop_agent_message_and_pending_inbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='pending_mode',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='agent',
            name='phase',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='agent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
