# Generated by Django 6.0.2 on 2026-02-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0027_add_agent_updated_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='agentevent',
            index=models.Index(fields=['agent', 'created_at'], name='agents_agen_agent_i_7b900f_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionresult',
            index=models.Index(fields=['agent', 'created_at'], name='agents_sess_agent_i_b7925c_idx'),
        ),
    ]
