# Generated by Django 6.0.2 on 2026-02-21 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0028_add_feed_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('event_type', models.CharField(max_length=50)),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_events', to='agents.agent')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['agent', 'created_at'], name='agents_stre_agent_i_3fac22_idx'), models.Index(fields=['agent', 'session_id', 'created_at'], name='agents_stre_agent_i_5e970d_idx')],
            },
        ),
    ]
