# Generated by Django 6.0.2 on 2026-02-21 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0029_add_stream_event'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='agentevent',
            name='agents_agen_agent_i_7b900f_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='agents_mess_agent_i_44149d_idx',
        ),
        migrations.RemoveConstraint(
            model_name='message',
            name='unique_agent_message_id',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='last_heartbeat_at',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='pending_input',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='pending_mode',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='pending_signal',
        ),
        migrations.RemoveField(
            model_name='message',
            name='agent',
        ),
        migrations.DeleteModel(
            name='AgentEvent',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
