# Generated by Django 6.0.2 on 2026-02-22 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0030_drop_legacy_models_and_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='cwd',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='transcript_path',
        ),
    ]
