# Generated by Django 6.0.2 on 2026-02-26 20:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0031_remove_agent_cwd_remove_agent_transcript_path"),
        ("projects", "0004_project_archived_at_project_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="attention_level",
            field=models.CharField(default="none", max_length=20),
        ),
        migrations.AddField(
            model_name="agent",
            name="duration_ms",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agent",
            name="last_output",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="agent",
            name="live_action",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="agent",
            name="mode",
            field=models.CharField(default="auto", max_length=20),
        ),
        migrations.AddField(
            model_name="agent",
            name="num_turns",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agent",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="agent",
            name="task",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="agent",
            name="status",
            field=models.CharField(
                choices=[
                    ("deploying", "Deploying"),
                    ("running", "Running"),
                    ("waiting", "Waiting"),
                    ("idle", "Idle"),
                    ("stopped", "Stopped"),
                    ("error", "Error"),
                ],
                default="deploying",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TeamFeedItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("type", models.CharField(max_length=30)),
                (
                    "agent_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("text", models.TextField(blank=True, default="")),
                ("command", models.TextField(blank=True, default="")),
                ("risk", models.CharField(blank=True, default="", max_length=200)),
                (
                    "perm_status",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "tool_use_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("title", models.CharField(blank=True, default="", max_length=500)),
                ("plan", models.TextField(blank=True, default="")),
                (
                    "plan_status",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("summary", models.TextField(blank=True, default="")),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                ("turns", models.IntegerField(blank=True, null=True)),
                ("duration", models.CharField(blank=True, default="", max_length=30)),
                ("is_error", models.BooleanField(blank=True, null=True)),
                (
                    "from_value",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("to_value", models.CharField(blank=True, default="", max_length=100)),
                ("target", models.CharField(blank=True, default="", max_length=100)),
                ("question", models.CharField(blank=True, default="", max_length=1000)),
                ("options", models.JSONField(blank=True, default=list)),
                ("questions", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feed_items",
                        to="agents.agent",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_items",
                        to="projects.project",
                    ),
                ),
                (
                    "source_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="agents.streamevent",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "created_at"],
                        name="agents_team_project_296fd3_idx",
                    ),
                    models.Index(
                        fields=["project", "agent_name", "type", "perm_status"],
                        name="agents_team_project_e7fd6f_idx",
                    ),
                ],
            },
        ),
    ]
