# Generated by Django 6.0.2 on 2026-02-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0036_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='assigned_to_all',
            field=models.BooleanField(default=False),
        ),
    ]
