# Generated by Django 6.0.2 on 2026-02-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0037_add_skill_assigned_to_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='allowed_tools',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
