# Generated by Django 6.0.2 on 2026-03-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0039_agent_relay_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentfeedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teamfeeditem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='relay_token',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='teamfeeditem',
            name='type',
            field=models.CharField(choices=[('system', 'System'), ('user', 'User'), ('summary', 'Summary'), ('status', 'Status'), ('error', 'Error'), ('question', 'Question'), ('plan', 'Plan'), ('permission', 'Permission'), ('multi-question', 'Multi Question'), ('agent-message', 'Agent Message'), ('task', 'Task')], max_length=30),
        ),
    ]
