# Generated by Django 6.0.2 on 2026-03-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0040_agentfeedback_updated_at_teamfeeditem_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
