# Generated by Django 6.0.2 on 2026-03-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0041_add_agent_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='relay_disconnected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
