# Generated by Django 6.0.2 on 2026-03-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0042_add_relay_disconnected_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamevent',
            name='is_canonical',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
