from __future__ import annotations

import argparse
import asyncio
import contextlib
import hashlib
import io
import json
import os
import shlex
import signal
import subprocess
import sys
import time
import uuid
from dataclasses import asdict, dataclass
from pathlib import Path
from urllib.parse import urlparse
from typing import Any, Callable

import modal


DEFAULT_CALLBACK_URL = "https://example.com/graphql"


class ModalHarnessError(RuntimeError):
    """Raised when the managed Modal harness cannot prove the runtime contract."""


@dataclass(frozen=True)
class ModalHarnessResult:
    sandbox_id: str
    container_id: str
    image_ref: str
    root_dir: str
    vnc_url: str
    health_url: str
    status_payload: dict[str, Any]
    runtime_log_tail: str


class TeeStream(io.TextIOBase):
    def __init__(self, *streams: io.TextIOBase) -> None:
        self._streams = streams

    def write(self, s: str) -> int:
        for stream in self._streams:
            try:
                stream.write(s)
                stream.flush()
            except ValueError:
                continue
        return len(s)

    def flush(self) -> None:
        for stream in self._streams:
            try:
                stream.flush()
            except ValueError:
                continue


def repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def agent_root() -> Path:
    return Path(__file__).resolve().parents[1]


def container_id_from_tunnel_url(url: str) -> str:
    if not url:
        return ""
    host = urlparse(url).hostname or ""
    if not host:
        return ""
    return host.split("-6080-", 1)[0].split("-8080-", 1)[0]


def required_env(name: str) -> str:
    value = os.environ.get(name, "").strip()
    if not value:
        raise ModalHarnessError(f"{name} is required")
    return value


def current_git_commit() -> str:
    try:
        return (
            subprocess.run(
                ["git", "rev-parse", "HEAD"],
                cwd=repo_root(),
                check=True,
                capture_output=True,
                text=True,
            )
            .stdout.strip()
        )
    except Exception:
        return ""


def render_local_desktop_managed_dockerfile() -> str:
    managed_lines = rewrite_dockerfile_heredoc_copies((agent_root() / "Dockerfile.managed").read_text().splitlines())
    desktop_lines = rewrite_dockerfile_heredoc_copies((agent_root() / "Dockerfile.desktop.managed").read_text().splitlines())

    while desktop_lines and (
        desktop_lines[0].startswith("ARG BASE_IMAGE=") or desktop_lines[0].startswith("FROM ${BASE_IMAGE}")
    ):
        desktop_lines.pop(0)

    return "\n".join(
        [
            "# GENERATED by modal_managed_harness.py for local-direct Modal debug builds.",
            *managed_lines,
            "",
            "# --- Desktop managed layer ---",
            *desktop_lines,
            "",
        ]
    )


def rewrite_dockerfile_heredoc_copies(lines: list[str]) -> list[str]:
    rewritten: list[str] = []
    i = 0
    while i < len(lines):
        line = lines[i]
        if line.startswith("COPY <<'") and " /" in line:
            target = line.rsplit(" ", 1)[-1]
            sentinel = line.split("<<", 1)[1].split("'", 2)[1]
            body: list[str] = []
            i += 1
            while i < len(lines) and lines[i] != sentinel:
                body.append(lines[i])
                i += 1
            if i == len(lines):
                raise ModalHarnessError(f"unterminated heredoc COPY in generated Dockerfile for {target}")
            quoted_body = " ".join(shlex.quote(entry) for entry in body)
            rewritten.append(
                f"RUN mkdir -p {shlex.quote(str(Path(target).parent))} "
                f"&& printf '%s\\n' {quoted_body} > {shlex.quote(target)}"
            )
        else:
            rewritten.append(line)
        i += 1
    return rewritten


def local_direct_modal_image(*, force_build: bool = False) -> modal.Image:
    dockerfile_text = render_local_desktop_managed_dockerfile()
    digest = hashlib.sha256(dockerfile_text.encode("utf-8")).hexdigest()[:12]
    generated_dir = repo_root() / ".codex" / "modal"
    generated_dir.mkdir(parents=True, exist_ok=True)
    dockerfile_path = generated_dir / f"desktop-managed-local-{digest}.Dockerfile"
    dockerfile_path.write_text(dockerfile_text)

    git_commit = current_git_commit()
    build_args = {"AGENTOBOX_GIT_COMMIT": git_commit} if git_commit else {}
    return modal.Image.from_dockerfile(
        dockerfile_path,
        context_dir=agent_root(),
        force_build=force_build,
        build_args=build_args,
    )


async def write_text(sb, path: str, content: str) -> None:
    handle = await sb.open.aio(path, "w")
    await handle.write.aio(content)
    await handle.close.aio()


async def exec_checked(sb, *cmd: str) -> str:
    proc = await sb.exec.aio(*cmd)
    await proc.wait.aio()
    stdout = await proc.stdout.read.aio()
    if proc.returncode != 0:
        stderr = ""
        try:
            stderr = await proc.stderr.read.aio()
        except Exception:
            pass
        raise ModalHarnessError(
            f"modal exec failed rc={proc.returncode}: {' '.join(cmd)}\nstdout:\n{stdout}\nstderr:\n{stderr}"
        )
    return stdout


async def http_get_json(sb, path: str) -> dict[str, Any]:
    payload = await exec_checked(
        sb,
        "python",
        "-c",
        (
            "import json,urllib.request;"
            f"resp=urllib.request.urlopen('http://127.0.0.1:8080{path}', timeout=5);"
            "print(json.dumps(json.load(resp)))"
        ),
    )
    return json.loads(payload)


async def runtime_log_tail(sb, root_dir: str, *, lines: int = 80) -> str:
    log_path = Path(root_dir) / "_abox" / "logs" / "runtime.jsonl"
    try:
        return await exec_checked(sb, "bash", "-lc", f"tail -n {lines} {log_path} 2>/dev/null || true")
    except Exception as exc:
        return f"(runtime log unavailable: {exc})"


async def sandbox_stderr_tail(sb, *, chars: int = 4000) -> str:
    try:
        stderr = await sb.stderr.read.aio()
    except Exception:
        return ""
    if not stderr:
        return ""
    return stderr[-chars:]


async def wait_for_stop_or_exit(
    sb,
    *,
    stop: asyncio.Event,
    root_dir: str,
    poll_interval_s: float = 2.0,
) -> None:
    while True:
        if stop.is_set():
            return
        result = await sb.poll.aio()
        if result is not None:
            stderr = await sandbox_stderr_tail(sb)
            log_tail = await runtime_log_tail(sb, root_dir)
            raise ModalHarnessError(
                f"managed modal debug sandbox exited after becoming ready rc={result}\n"
                f"sandbox_id={sb.object_id}\n"
                f"stderr:\n{stderr}\n"
                f"runtime_log_tail:\n{log_tail}"
            )
        await asyncio.sleep(poll_interval_s)


def desktop_surface_ready(status: dict[str, Any]) -> bool:
    services = status.get("services", {})
    required = ("xvfb", "x11vnc", "websockify", "awesome")
    return all(services.get(name) == "up" for name in required)


def required_services_ready(status: dict[str, Any], required_services: tuple[str, ...]) -> bool:
    services = status.get("services", {})
    return all(services.get(name) == "up" for name in required_services)


async def provision_minimal_managed_root(sb, *, root_dir: str, relay_token: str) -> None:
    await exec_checked(
        sb,
        "bash",
        "-lc",
        (
            f"mkdir -p {root_dir}/home/agent {root_dir}/_abox "
            f"{root_dir}/tmp/abox-theme {root_dir}/mnt/abox-state/secrets"
        ),
    )
    await write_text(sb, f"{root_dir}/home/agent/.relay_env", f"RELAY_AUTH_TOKEN={relay_token}\n")
    await write_text(sb, f"{root_dir}/_abox/state.json", "{}")
    await write_text(sb, f"{root_dir}/_abox/status.json", "{}")
    await write_text(sb, f"{root_dir}/_abox/provisioned.ready", relay_token)
    await exec_checked(sb, "bash", "-lc", f"chown -R agent:agent {root_dir}")


async def run_managed_modal_contract(
    *,
    image_ref: str | None = None,
    callback_url: str = DEFAULT_CALLBACK_URL,
    timeout_s: float = 60.0,
    stability_window_s: float = 0.0,
    sandbox_timeout_s: int = 300,
    idle_timeout_s: int | None = None,
    app_name: str = "agentobox",
    root_dir_base: str = "/tmp/agentobox-contract",
    require_transport: bool = True,
    required_services: tuple[str, ...] = (),
    keep_alive_until: asyncio.Event | None = None,
    on_ready: Callable[[ModalHarnessResult], None] | None = None,
    local_direct: bool = False,
    force_build: bool = False,
) -> ModalHarnessResult:
    app = await modal.App.lookup.aio(app_name, create_if_missing=True)

    agent_id = f"modal-contract-{uuid.uuid4().hex[:8]}"
    relay_token = f"token-{uuid.uuid4().hex}"
    root_dir = f"{root_dir_base.rstrip('/')}/{agent_id}"

    env = {
        "AGENTOBOX_MODE": "managed",
        "AGENTOBOX_PLATFORM": "modal",
        "AGENTOBOX_RUNTIME_PROFILE": "desktop",
        "AGENTOBOX_EXECUTOR": "echo",
        "AGENTOBOX_BIND_HOST": "0.0.0.0",
        "AGENTOBOX_PORT": "8080",
        "AGENTOBOX_ROOT_DIR": root_dir,
        "AGENT_HOME": "/home/agent",
        "AGENT_ID": agent_id,
        "ABOX_CALLBACK_URL": callback_url,
        "RELAY_AUTH_TOKEN": relay_token,
        "DISPLAY": ":99",
        "RESOLUTION": "1920x1080",
    }

    if local_direct:
        image = local_direct_modal_image(force_build=force_build)
        resolved_image_ref = image_ref or "local-direct"
    else:
        if not image_ref:
            raise ModalHarnessError("image_ref is required unless local_direct is enabled")
        image = modal.Image.from_registry(
            image_ref,
            secret=modal.Secret.from_name("ghcr-secret"),
        )
        resolved_image_ref = image_ref

    sb = None
    try:
        sb = await modal.Sandbox.create.aio(
            app=app,
            image=image,
            secrets=[modal.Secret.from_dict(env)],
            encrypted_ports=[6080, 8080],
            timeout=sandbox_timeout_s,
            idle_timeout=idle_timeout_s,
            cpu=2.0,
            memory=4096,
        )

        await provision_minimal_managed_root(sb, root_dir=root_dir, relay_token=relay_token)

        deadline = time.monotonic() + timeout_s
        last_error = ""
        last_status: dict[str, Any] = {}
        stable_since: float | None = None
        while time.monotonic() < deadline:
            result = await sb.poll.aio()
            if result is not None:
                stderr = ""
                try:
                    stderr = await sb.stderr.read.aio()
                except Exception:
                    pass
                raise ModalHarnessError(
                    f"managed modal contract sandbox exited early rc={result}\nsandbox_id={sb.object_id}\nstderr:\n{stderr[-4000:]}"
                )
            try:
                livez = await http_get_json(sb, "/livez")
                status = await http_get_json(sb, "/status")
                last_status = status
                if livez != {"status": "ok"}:
                    raise ModalHarnessError(f"unexpected livez payload: {livez}")
                if status["mode"] != "managed":
                    raise ModalHarnessError(f"unexpected mode: {status['mode']}")
                if status["platform"] != "modal":
                    raise ModalHarnessError(f"unexpected platform: {status['platform']}")
                if status["profile"] != "desktop":
                    raise ModalHarnessError(f"unexpected profile: {status['profile']}")
                if not desktop_surface_ready(status):
                    stable_since = None
                    raise ModalHarnessError(f"desktop surface not ready: {status.get('services', {})}")

                log_tail = await runtime_log_tail(sb, root_dir)
                if require_transport:
                    transport = status.get("transport", {})
                    if not transport.get("enabled"):
                        stable_since = None
                        raise ModalHarnessError("transport is not enabled")
                    if transport.get("state") not in {"connected", "degraded", "connecting"}:
                        stable_since = None
                        raise ModalHarnessError(f"unexpected transport state: {transport.get('state')}")
                if required_services and not required_services_ready(status, required_services):
                    stable_since = None
                    raise ModalHarnessError(
                        f"required services not ready: expected {required_services}, got {status.get('services', {})}"
                    )

                now = time.monotonic()
                if stable_since is None:
                    stable_since = now
                if now - stable_since < stability_window_s:
                    await asyncio.sleep(1)
                    continue

                tunnels = await sb.tunnels.aio()
                result = ModalHarnessResult(
                    sandbox_id=sb.object_id,
                    container_id=container_id_from_tunnel_url(tunnels[6080].url if 6080 in tunnels else ""),
                    image_ref=resolved_image_ref,
                    root_dir=root_dir,
                    vnc_url=tunnels[6080].url if 6080 in tunnels else "",
                    health_url=tunnels[8080].url if 8080 in tunnels else "",
                    status_payload=status,
                    runtime_log_tail=log_tail,
                )
                if on_ready is not None:
                    on_ready(result)
                if keep_alive_until is not None:
                    await wait_for_stop_or_exit(
                        sb,
                        stop=keep_alive_until,
                        root_dir=root_dir,
                    )
                    await sb.terminate.aio()
                    sb = None
                    return result
                await sb.terminate.aio()
                sb = None
                return result
            except Exception as exc:
                last_error = str(exc)
                await asyncio.sleep(2)

        log_tail = await runtime_log_tail(sb, root_dir) if sb is not None else ""
        raise ModalHarnessError(
            f"managed modal contract did not become healthy in time: {last_error}\n"
            f"sandbox_id={sb.object_id if sb is not None else ''}\n"
            f"last_status={last_status}\n"
            f"runtime_log_tail=\n{log_tail}"
        )
    finally:
        if sb is not None and keep_alive_until is None:
            await sb.terminate.aio()


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Managed Modal runtime debug/contract harness")
    parser.add_argument("--image-ref", default=os.environ.get("AGENTOBOX_MODAL_CONTRACT_IMAGE", "").strip())
    parser.add_argument("--callback-url", default=os.environ.get("AGENTOBOX_MODAL_CONTRACT_CALLBACK_URL", DEFAULT_CALLBACK_URL))
    parser.add_argument("--timeout-s", type=float, default=float(os.environ.get("AGENTOBOX_MODAL_CONTRACT_TIMEOUT_S", "60")))
    parser.add_argument(
        "--stability-window-s",
        type=float,
        default=float(os.environ.get("AGENTOBOX_MODAL_CONTRACT_STABILITY_WINDOW_S", "0")),
        help="require the runtime to remain healthy for this many seconds before succeeding",
    )
    parser.add_argument(
        "--sandbox-timeout-s",
        type=int,
        default=int(os.environ.get("AGENTOBOX_MODAL_SANDBOX_TIMEOUT_S", "0") or "0"),
        help="Modal Sandbox lifetime in seconds; defaults to 1h for --keep-alive and 5m otherwise",
    )
    parser.add_argument(
        "--idle-timeout-s",
        type=int,
        default=int(os.environ.get("AGENTOBOX_MODAL_IDLE_TIMEOUT_S", "0") or "0"),
        help="optional Modal Sandbox idle timeout in seconds; 0 disables explicit idle timeout",
    )
    parser.add_argument("--app-name", default=os.environ.get("MODAL_APP_NAME", "agentobox"))
    parser.add_argument("--root-dir-base", default=os.environ.get("AGENTOBOX_MODAL_CONTRACT_ROOT_BASE", "/tmp/agentobox-contract"))
    parser.add_argument("--keep-alive", action="store_true", default=os.environ.get("AGENTOBOX_MODAL_CONTRACT_KEEP_ALIVE") == "1")
    parser.add_argument(
        "--isolated",
        action="store_true",
        default=os.environ.get("AGENTOBOX_MODAL_CONTRACT_ISOLATED") == "1",
        help="allow degraded transport when exercising the runtime without a real backend callback",
    )
    parser.add_argument(
        "--result-file",
        default=os.environ.get("AGENTOBOX_MODAL_CONTRACT_RESULT_FILE", "").strip(),
        help="optional path to write the harness result JSON for later inspection",
    )
    parser.add_argument(
        "--log-file",
        default=os.environ.get("AGENTOBOX_MODAL_CONTRACT_LOG_FILE", "").strip(),
        help="optional path to tee harness/build/runtime output for later inspection",
    )
    parser.add_argument(
        "--local-direct",
        action="store_true",
        default=os.environ.get("AGENTOBOX_MODAL_CONTRACT_LOCAL_DIRECT") == "1",
        help="build the current repo's managed desktop image directly on Modal instead of pulling from GHCR",
    )
    parser.add_argument(
        "--force-build",
        action="store_true",
        default=os.environ.get("AGENTOBOX_MODAL_CONTRACT_FORCE_BUILD") == "1",
        help="force a fresh Modal image build when using --local-direct",
    )
    parser.add_argument(
        "--require-service",
        action="append",
        default=[],
        help="service name that must remain up before the contract succeeds; may be passed multiple times",
    )
    parser.add_argument("--json", action="store_true", help="print machine-readable result JSON")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    image_ref = args.image_ref or os.environ.get("AGENTOBOX_MODAL_CONTRACT_IMAGE", "").strip()
    if not image_ref and not args.local_direct:
        print("AGENTOBOX_MODAL_CONTRACT_IMAGE or --image-ref is required", file=sys.stderr)
        return 2

    def emit_result(result: ModalHarnessResult) -> None:
        result_json = json.dumps(asdict(result), indent=2)
        if args.result_file:
            result_path = Path(args.result_file)
            result_path.parent.mkdir(parents=True, exist_ok=True)
            result_path.write_text(result_json + "\n")
        if args.json:
            print(result_json)
        else:
            print(f"sandbox_id: {result.sandbox_id}")
            print(f"image_ref: {result.image_ref}")
            print(f"root_dir: {result.root_dir}")
            print(f"health_url: {result.health_url or '(none)'}")
            print(f"vnc_url: {result.vnc_url or '(none)'}")
            print("status_payload:")
            print(json.dumps(result.status_payload, indent=2))
            print("runtime_log_tail:")
            print(result.runtime_log_tail.rstrip() or "(empty)")
            if args.keep_alive:
                print(f"modal shell {result.sandbox_id}")

    async def run_cli() -> ModalHarnessResult:
        stop: asyncio.Event | None = None
        if args.keep_alive:
            stop = asyncio.Event()
            loop = asyncio.get_running_loop()
            for sig in (signal.SIGINT, signal.SIGTERM):
                try:
                    loop.add_signal_handler(sig, stop.set)
                except NotImplementedError:
                    pass
        sandbox_timeout_s = args.sandbox_timeout_s or (3600 if args.keep_alive else 300)
        idle_timeout_s = args.idle_timeout_s or None
        return await run_managed_modal_contract(
            image_ref=image_ref,
            callback_url=args.callback_url,
            timeout_s=args.timeout_s,
            stability_window_s=args.stability_window_s,
            sandbox_timeout_s=sandbox_timeout_s,
            idle_timeout_s=idle_timeout_s,
            app_name=args.app_name,
            root_dir_base=args.root_dir_base,
            require_transport=not args.isolated,
            required_services=tuple(args.require_service),
            keep_alive_until=stop,
            on_ready=emit_result,
            local_direct=args.local_direct,
            force_build=args.force_build,
        )

    try:
        output_context = modal.enable_output() if args.local_direct else contextlib.nullcontext()
        if args.log_file:
            log_path = Path(args.log_file)
            log_path.parent.mkdir(parents=True, exist_ok=True)
            with log_path.open("w", encoding="utf-8") as log_fp:
                tee_out = TeeStream(sys.stdout, log_fp)
                tee_err = TeeStream(sys.stderr, log_fp)
                with contextlib.redirect_stdout(tee_out), contextlib.redirect_stderr(tee_err), output_context:
                    asyncio.run(run_cli())
        else:
            with output_context:
                asyncio.run(run_cli())
    except ModalHarnessError as exc:
        print(str(exc), file=sys.stderr)
        return 1
    if args.keep_alive:
        print("keeping sandbox alive; press Ctrl-C to terminate", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
