# Generated by Django 6.0.2 on 2026-02-07 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="anthropic_api_key",
        ),
        migrations.RemoveField(
            model_name="project",
            name="default_runtime",
        ),
    ]
