#!/command/with-contenv bash
exec 2>&1
source /etc/s6-overlay/scripts/preflight

preflight --service svc-websockify --env DISPLAY

exec abox-exec --service svc-websockify -- websockify --web /opt/noVNC 6080 localhost:5900
