"""Runtime-owned desktop configuration bridge.

The desktop profile projects only the files the window manager needs from the
canonical runtime tree. The browser is a separate app-level service and does
not participate in theme projection.
"""

from __future__ import annotations

from pathlib import Path

from agent.provisioning.manifest import CANONICAL_PATHS


def default_browser_url(root_dir: Path) -> str:
    return (root_dir / CANONICAL_PATHS["browser_home_html"]).resolve().as_uri()


def ensure_desktop_runtime_files(root_dir: Path, *, agent_home: Path = Path("/home/agent")) -> None:
    """Write the runtime-owned desktop config files for the desktop profile."""

    awesome_rc = root_dir / CANONICAL_PATHS["desktop_awesome_rc"]
    awesome_rc.parent.mkdir(parents=True, exist_ok=True)
    awesome_rc.write_text(render_awesome_rc(root_dir, agent_home=agent_home))


def render_awesome_rc(root_dir: Path, *, agent_home: Path = Path("/home/agent")) -> str:
    """Render a visible AwesomeWM desktop bound to the canonical theme artifact."""

    theme_path = root_dir / CANONICAL_PATHS["theme_awesome_lua"]
    browser_bin = "/usr/bin/chromium"
    browser_url = default_browser_url(root_dir)
    browser_icon = "/usr/share/icons/hicolor/48x48/apps/chromium.png"
    xterm_icon = "/usr/share/pixmaps/xterm-color_48x48.xpm"

    browser_command = (
        f"HOME='{agent_home}' DISPLAY=':99' {browser_bin} "
        "--no-sandbox "
        "--disable-dev-shm-usage "
        "--disable-gpu "
        "--no-first-run "
        "--no-default-browser-check "
        "--ozone-platform=x11 "
        f"--user-data-dir='{agent_home}/.config/chromium/agentobox' "
        f"--new-window {browser_url}"
    )

    return f"""-- Generated by agent.runtime.desktop.config. Do not edit manually.
local awful = require("awful")
local gears = require("gears")
local wibox = require("wibox")
local beautiful = require("beautiful")

local theme_path = "{theme_path}"
local theme_tokens = {{}}

local function load_theme_tokens()
    local ok, loaded = pcall(dofile, theme_path)
    if ok and type(loaded) == "table" then
        theme_tokens = loaded
        return loaded
    end
    theme_tokens = {{}}
    return theme_tokens
end

local function apply_theme()
    local tokens = load_theme_tokens()
    local surface = tokens["surface"] or "#1e1e1e"
    local surface_raised = tokens["surface-raised"] or surface
    local text_default = tokens["text-default"] or "#d4d4d4"
    local border_default = tokens["border-default"] or surface_raised
    local accent = tokens["accent"] or surface_raised

    beautiful.init({{
        bg_normal = surface,
        bg_focus = surface_raised,
        fg_normal = text_default,
        fg_focus = text_default,
        border_width = 2,
        border_normal = border_default,
        border_focus = accent,
        wallpaper = surface,
    }})

    for s in screen do
        gears.wallpaper.set(surface, s)
        if s.dock then
            s.dock.bg = surface
        end
    end

    for _, c in ipairs(client.get()) do
        if c == client.focus then
            c.border_color = beautiful.border_focus
        else
            c.border_color = beautiful.border_normal
        end
    end
end

_G.agentobox_apply_theme = apply_theme

apply_theme()

screen.connect_signal("request::wallpaper", function(s)
    gears.wallpaper.set(beautiful.wallpaper or "#1e1e1e", s)
end)

local launcher_browser = awful.widget.launcher({{
    image = "{browser_icon}",
    command = "{browser_command}",
}})

local launcher_terminal = awful.widget.launcher({{
    image = "{xterm_icon}",
    command = "xterm",
}})

awful.screen.connect_for_each_screen(function(s)
    awful.tag({{ "1" }}, s, awful.layout.suit.max)

    s.dock = awful.wibar({{
        position = "bottom",
        screen = s,
        height = 48,
        bg = beautiful.bg_normal,
    }})

    s.dock:setup({{
        layout = wibox.layout.align.horizontal,
        expand = "none",
        nil,
        {{
            layout = wibox.layout.fixed.horizontal,
            spacing = 10,
            wibox.container.margin(launcher_browser, 4, 4, 8, 8),
            wibox.container.margin(launcher_terminal, 4, 4, 8, 8),
        }},
        nil,
    }})
end)

client.connect_signal("request::titlebars", function() end)

awful.rules.rules = {{
    {{
        rule = {{}},
        properties = {{
            focus = awful.client.focus.filter,
            raise = true,
            screen = awful.screen.preferred,
            placement = awful.placement.no_overlap + awful.placement.no_offscreen,
            maximized = true,
            border_width = beautiful.border_width,
            border_color = beautiful.border_normal,
        }},
    }},
}}

client.connect_signal("mouse::enter", function(c)
    c:emit_signal("request::activate", "mouse_enter", {{ raise = false }})
end)

client.connect_signal("focus", function(c)
    c.border_color = beautiful.border_focus
end)

client.connect_signal("unfocus", function(c)
    c.border_color = beautiful.border_normal
end)

client.connect_signal("property::maximized", function(c)
    if c.maximized then
        c.border_width = 0
    else
        c.border_width = beautiful.border_width
    end
end)

client.connect_signal("manage", function(c)
    if c.maximized then
        c.border_width = 0
    end
end)
"""
