"""Runtime-owned desktop configuration bridge.

Desktop services should consume runtime-generated files the same way every
other runtime facet does. This module writes the minimal consumer-native files
that bind desktop processes back to the canonical runtime-visible artifacts.
"""

from __future__ import annotations

import shutil
from pathlib import Path


from agent.provisioning.manifest import CANONICAL_PATHS


def ensure_desktop_runtime_files(root_dir: Path) -> None:
    """Write the runtime-owned desktop config files for the desktop profile."""

    awesome_rc = root_dir / CANONICAL_PATHS["desktop_awesome_rc"]
    awesome_rc.parent.mkdir(parents=True, exist_ok=True)
    awesome_rc.write_text(render_awesome_rc(root_dir))

    firefox_config_css = root_dir / CANONICAL_PATHS["desktop_firefox_config_css"]
    firefox_config_css.parent.mkdir(parents=True, exist_ok=True)
    firefox_config_css.write_text(render_firefox_config_css())

    firefox_overrides = root_dir / CANONICAL_PATHS["desktop_firefox_overrides_js"]
    firefox_overrides.parent.mkdir(parents=True, exist_ok=True)
    firefox_overrides.write_text(render_firefox_user_overrides_js())


def render_awesome_rc(root_dir: Path) -> str:
    """Render a visible AwesomeWM desktop bound to the canonical theme artifact."""

    theme_path = root_dir / CANONICAL_PATHS["theme_awesome_lua"]
    return f"""-- Generated by agent.runtime.desktop.config. Do not edit manually.
local awful = require("awful")
local gears = require("gears")
local wibox = require("wibox")
local beautiful = require("beautiful")

local theme_path = "{theme_path}"
local theme_tokens = {{}}

local function load_theme_tokens()
    local ok, loaded = pcall(dofile, theme_path)
    if ok and type(loaded) == "table" then
        theme_tokens = loaded
        return loaded
    end
    theme_tokens = {{}}
    return theme_tokens
end

local function apply_theme()
    local tokens = load_theme_tokens()
    local surface = tokens["surface"] or "#1e1e1e"
    local surface_raised = tokens["surface-raised"] or surface
    local text_default = tokens["text-default"] or "#d4d4d4"
    local border_default = tokens["border-default"] or surface_raised
    local accent = tokens["accent"] or surface_raised

    beautiful.init({{
        bg_normal = surface,
        bg_focus = surface_raised,
        fg_normal = text_default,
        fg_focus = text_default,
        border_width = 2,
        border_normal = border_default,
        border_focus = accent,
        wallpaper = surface,
    }})

    for s in screen do
        gears.wallpaper.set(surface, s)
        if s.dock then
            s.dock.bg = surface
        end
    end

    for _, c in ipairs(client.get()) do
        if c == client.focus then
            c.border_color = beautiful.border_focus
        else
            c.border_color = beautiful.border_normal
        end
    end
end

_G.agentobox_apply_theme = apply_theme

apply_theme()

screen.connect_signal("request::wallpaper", function(s)
    gears.wallpaper.set(beautiful.wallpaper or "#1e1e1e", s)
end)

local firefox_icon = "/usr/share/icons/hicolor/48x48/apps/firefox-esr.png"
local xterm_icon = "/usr/share/pixmaps/xterm-color_48x48.xpm"

local launcher_firefox = awful.widget.launcher({{
    image = firefox_icon,
    command = "firefox-esr",
}})

local launcher_terminal = awful.widget.launcher({{
    image = xterm_icon,
    command = "xterm",
}})

    awful.screen.connect_for_each_screen(function(s)
    awful.tag({{ "1" }}, s, awful.layout.suit.max)

    s.dock = awful.wibar({{
        position = "bottom",
        screen = s,
        height = 48,
        bg = beautiful.bg_normal,
    }})

    s.dock:setup({{
        layout = wibox.layout.align.horizontal,
        expand = "none",
        nil,
        {{
            layout = wibox.layout.fixed.horizontal,
            spacing = 10,
            wibox.container.margin(launcher_firefox, 4, 4, 8, 8),
            wibox.container.margin(launcher_terminal, 4, 4, 8, 8),
        }},
        nil,
    }})
end)

client.connect_signal("request::titlebars", function() end)

awful.rules.rules = {{
    {{
        rule = {{}},
        properties = {{
            focus = awful.client.focus.filter,
            raise = true,
            screen = awful.screen.preferred,
            placement = awful.placement.no_overlap + awful.placement.no_offscreen,
            maximized = true,
            border_width = beautiful.border_width,
            border_color = beautiful.border_normal,
        }},
    }},
}}

client.connect_signal("mouse::enter", function(c)
    c:emit_signal("request::activate", "mouse_enter", {{ raise = false }})
end)

client.connect_signal("focus", function(c)
    c.border_color = beautiful.border_focus
end)

client.connect_signal("unfocus", function(c)
    c.border_color = beautiful.border_normal
end)

client.connect_signal("property::maximized", function(c)
    if c.maximized then
        c.border_width = 0
    else
        c.border_width = beautiful.border_width
    end
end)

client.connect_signal("manage", function(c)
    if c.maximized then
        c.border_width = 0
    end
end)
"""


def render_firefox_config_css() -> str:
    """Render the runtime-owned Firefox chrome override bridge."""

    return """/* Generated by agent.runtime.desktop.config. Do not edit manually.
   Theme colors come from /tmp/abox-theme/userChrome.css, loaded dynamically
   by Firefox autoconfig via the runtime's loopback reload signal.
   DO NOT @import the theme CSS here — imports are cached at startup. */

:root {
  --tf-font-family: "JetBrains Mono", "SF Mono", Consolas, monospace;
  --tf-display-horizontal-tabs: block;
  --tf-display-nav-buttons: flex;
}
"""


def render_firefox_user_overrides_js() -> str:
    """Render stable Firefox prefs for the desktop profile."""

    return """// Generated by agent.runtime.desktop.config. Do not edit manually.
// Additional Firefox prefs for the Agentobox desktop runtime.

user_pref("ui.systemUsesDarkTheme", 1);
user_pref("layout.css.prefers-color-scheme.content-override", 0);
user_pref("browser.in-content.dark-mode", true);

user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage_override.mstone", "ignore");
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("browser.aboutwelcome.enabled", false);
user_pref("browser.newtabpage.activity-stream.feeds.topsites", false);

user_pref("security.enterprise_roots.enabled", true);
user_pref("network.stricttransportsecurity.preloadlist", false);
user_pref("security.cert_pinning.enforcement_level", 0);

user_pref("security.sandbox.warn_unprivileged_namespaces", false);
user_pref("browser.toolbars.bookmarks.visibility", "never");
user_pref("app.update.enabled", false);
user_pref("app.update.auto", false);
user_pref("toolkit.cosmeticAnimations.enabled", false);
user_pref("ui.prefersReducedMotion", 1);
"""


def render_firefox_autoconfig_js() -> str:
    """Render Firefox's static autoconfig toggle for the desktop image."""

    return """pref("general.config.filename", "mozilla.cfg");
pref("general.config.obscure_value", 0);
pref("general.config.sandbox_enabled", false);
"""


def render_firefox_mozilla_cfg() -> str:
    """Render the Firefox live-theme bridge used by the desktop runtime."""

    return """// Generated by agent.runtime.desktop.config. Do not edit manually.
try {
    let Cc = Components.classes;
    let Ci = Components.interfaces;

    let sss = Cc["@mozilla.org/content/style-sheet-service;1"]
        .getService(Ci.nsIStyleSheetService);
    let ios = Cc["@mozilla.org/network/io-service;1"]
        .getService(Ci.nsIIOService);

    let THEME_CSS = "file:///tmp/abox-theme/userChrome.css";
    let RELOAD_PORT = 9224;
    let _currentURI = null;

    function _reloadThemeCSS() {
        try {
            let freshURI = ios.newURI(THEME_CSS + "?t=" + Date.now(), null, null);
            sss.loadAndRegisterSheet(freshURI, sss.USER_SHEET);
            if (_currentURI && sss.sheetRegistered(_currentURI, sss.USER_SHEET)) {
                sss.unregisterSheet(_currentURI, sss.USER_SHEET);
            }
            _currentURI = freshURI;
        } catch (e) {
            Components.utils.reportError("abox: theme reload failed: " + e);
        }
    }

    let obs = Cc["@mozilla.org/observer-service;1"]
        .getService(Ci.nsIObserverService);
    obs.addObserver({
        observe: function() {
            obs.removeObserver(this, "browser-delayed-startup-finished");
            _reloadThemeCSS();

            let server = Cc["@mozilla.org/network/server-socket;1"]
                .createInstance(Ci.nsIServerSocket);
            server.init(RELOAD_PORT, true, -1);
            server.asyncListen({
                onSocketAccepted: function(serv, transport) {
                    _reloadThemeCSS();
                    transport.close(0);
                },
                onStopListening: function() {}
            });

            if (typeof globalThis !== "undefined") {
                if (globalThis.__abox_theme_server) {
                    try { globalThis.__abox_theme_server.close(); } catch (_) {}
                }
                globalThis.__abox_theme_server = server;
            }
        }
    }, "browser-delayed-startup-finished", false);
} catch (e) {
    Components.utils.reportError("abox: theme reload setup failed: " + e);
}
"""


def ensure_firefox_system_files(firefox_root: Path = Path("/usr/lib/firefox-esr")) -> None:
    """Write Firefox's image-local autoconfig bridge files."""

    autoconfig = firefox_root / "defaults/pref/autoconfig.js"
    autoconfig.parent.mkdir(parents=True, exist_ok=True)
    autoconfig.write_text(render_firefox_autoconfig_js())

    mozilla_cfg = firefox_root / "mozilla.cfg"
    mozilla_cfg.parent.mkdir(parents=True, exist_ok=True)
    mozilla_cfg.write_text(render_firefox_mozilla_cfg())


def prepare_firefox_profile(
    root_dir: Path,
    *,
    agent_home: Path = Path("/home/agent"),
    textfox_root: Path = Path("/opt/textfox"),
) -> Path:
    """Create/update the deterministic Firefox profile used by the desktop runtime."""

    profile_dir = _ensure_firefox_profile_exists(agent_home)
    chrome_dir = profile_dir / "chrome"
    chrome_dir.mkdir(parents=True, exist_ok=True)

    textfox_chrome_dir = textfox_root / "chrome"
    if textfox_chrome_dir.exists():
        shutil.copytree(textfox_chrome_dir, chrome_dir, dirs_exist_ok=True)

    shutil.copyfile(
        root_dir / CANONICAL_PATHS["desktop_firefox_config_css"],
        chrome_dir / "config.css",
    )

    textfox_user_js = textfox_root / "user.js"
    user_js_path = profile_dir / "user.js"
    user_js = textfox_user_js.read_text() if textfox_user_js.exists() else ""
    overrides = (root_dir / CANONICAL_PATHS["desktop_firefox_overrides_js"]).read_text()
    user_js_path.write_text(user_js + overrides)
    return profile_dir


def _ensure_firefox_profile_exists(
    agent_home: Path,
) -> Path:
    firefox_dir = agent_home / ".mozilla/firefox"
    firefox_dir.mkdir(parents=True, exist_ok=True)
    profile_dir = firefox_dir / "agentobox.default"
    profile_dir.mkdir(parents=True, exist_ok=True)
    return profile_dir
