#!/usr/bin/env python3
"""
Theme token converter — generates derived theme files from tokens.json.

Called from:
1. Boot oneshot (init-volume) for initial state
2. Relay poke handler when tokens.json changes

Input:  /vol/tmp/abox-theme/tokens.json (CSS design tokens)
Output: /vol/tmp/abox-theme/userChrome.css (Firefox textfox overrides)
        /vol/tmp/abox-theme/awesome.lua (AwesomeWM theme table)
        /vol/tmp/abox-theme/theme.json (reference copy)
"""

import json
import sys
from pathlib import Path


def tokens_to_css(tokens: dict) -> str:
    """Generate CSS overrides for Firefox textfox from design tokens."""
    surface = tokens.get("surface", "#1e1e1e")
    surface_raised = tokens.get("surface-raised", surface)
    text_default = tokens.get("text-default", "#d4d4d4")
    text_muted = tokens.get("text-muted", "#888888")
    accent = tokens.get("accent", "#5a5a5a")
    border = tokens.get("border-default", surface_raised)
    border_subtle = tokens.get("border-subtle", surface_raised)

    return (
        "/* Generated by converters.py — do not edit manually */\n"
        ":root {\n"
        f"  --lwt-accent-color: {surface} !important;\n"
        f"  --lwt-text-color: {text_default} !important;\n"
        f"  --lwt-tab-line-color: {accent} !important;\n"
        f"  --toolbar-bgcolor: {surface} !important;\n"
        f"  --toolbar-color: {text_muted} !important;\n"
        f"  --toolbar-field-background-color: {surface} !important;\n"
        f"  --toolbar-field-color: {text_default} !important;\n"
        f"  --toolbar-field-border-color: {border_subtle} !important;\n"
        f"  --toolbar-field-focus-background-color: {surface} !important;\n"
        f"  --toolbar-field-focus-color: {text_default} !important;\n"
        f"  --arrowpanel-background: {surface} !important;\n"
        f"  --arrowpanel-color: {text_default} !important;\n"
        f"  --arrowpanel-border-color: {border} !important;\n"
        f"  --sidebar-background-color: {surface} !important;\n"
        f"  --sidebar-text-color: {text_muted} !important;\n"
        f"  --sidebar-border-color: {border_subtle} !important;\n"
        f"  --newtab-background-color: {surface} !important;\n"
        f"  --newtab-text-primary-color: {text_default} !important;\n"
        f"  --tf-bg: {surface} !important;\n"
        f"  --tf-border: {border} !important;\n"
        f"  --tf-accent: {accent} !important;\n"
        "}\n"
        "\n"
        "/* Direct element overrides — kill Firefox's default background-image\n"
        "   patterns (red diagonal stripes) that paint over CSS variables. */\n"
        f"#navigator-toolbox, #nav-bar, #PersonalToolbar {{\n"
        f"  background-color: {surface} !important;\n"
        f"  background-image: none !important;\n"
        f"}}\n"
        f"#urlbar-background {{\n"
        f"  background-color: {surface} !important;\n"
        f"  background-image: none !important;\n"
        f"}}\n"
        f"#urlbar-input-container {{\n"
        f"  background-color: {surface} !important;\n"
        f"  background-image: none !important;\n"
        f"}}\n"
    )


def tokens_to_lua(tokens: dict) -> str:
    """Generate Lua table for AwesomeWM from design tokens."""
    entries = ", ".join(f'["{k}"] = "{v}"' for k, v in sorted(tokens.items()))
    return f"return {{ {entries} }}\n"


def convert_theme(tokens_path: str) -> None:
    """Read tokens.json, write CSS/lua/json alongside it."""
    tokens_file = Path(tokens_path)
    tokens = json.loads(tokens_file.read_text())
    out_dir = tokens_file.parent

    (out_dir / "userChrome.css").write_text(tokens_to_css(tokens))
    (out_dir / "awesome.lua").write_text(tokens_to_lua(tokens))
    (out_dir / "theme.json").write_text(json.dumps(tokens, indent=2) + "\n")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <tokens.json path>", file=sys.stderr)
        sys.exit(1)
    convert_theme(sys.argv[1])
