"""Standardized error taxonomy for the agentobox platform.

Every ``except Exception`` block in the codebase must reference an error code
from this module. Codes follow the format ``ERR-<DOMAIN>-<DESCRIPTION>``.

Architecture check ``check_broad_except_has_error_metadata`` enforces that
every broad except in backend/agents/services/ logs with an ``error_code``.
"""

# ── Relay errors ──

ERR_RELAY_WS_DISCONNECTED = "ERR-RELAY-WS-DISCONNECTED"
ERR_RELAY_BUFFER_OVERFLOW = "ERR-RELAY-BUFFER-OVERFLOW"
ERR_RELAY_SDK_INIT_TIMEOUT = "ERR-RELAY-SDK-INIT-TIMEOUT"

# ── MCP errors ──

ERR_MCP_CONFIG_INVALID = "ERR-MCP-CONFIG-INVALID"
ERR_MCP_COORD_CONNECTIVITY = "ERR-MCP-COORD-CONNECTIVITY"
ERR_MCP_REGISTRY_UNSUPPORTED = "ERR-MCP-REGISTRY-UNSUPPORTED"
ERR_MCP_REGISTRY_LOOKUP_FAILED = "ERR-MCP-REGISTRY-LOOKUP-FAILED"

# ── Lifecycle errors ──

ERR_LIFECYCLE_PROVISION_FAILED = "ERR-LIFECYCLE-PROVISION-FAILED"
ERR_LIFECYCLE_PROVISION_ORPHANED = "ERR-LIFECYCLE-PROVISION-ORPHANED"
ERR_LIFECYCLE_PROVISION_CLEANUP_FAILED = "ERR-LIFECYCLE-PROVISION-CLEANUP-FAILED"
ERR_LIFECYCLE_STATE_ILLEGAL = "ERR-LIFECYCLE-STATE-ILLEGAL"
ERR_LIFECYCLE_RUNTIME_DEAD = "ERR-LIFECYCLE-RUNTIME-DEAD"
ERR_LIFECYCLE_STUCK_DEPLOY = "ERR-LIFECYCLE-STUCK-DEPLOY"
ERR_LIFECYCLE_TERMINATE_FAILED = "ERR-LIFECYCLE-TERMINATE-FAILED"
ERR_LIFECYCLE_LOG_CAPTURE_FAILED = "ERR-LIFECYCLE-LOG-CAPTURE-FAILED"
ERR_LIFECYCLE_SECRET_DECRYPT_FAILED = "ERR-LIFECYCLE-SECRET-DECRYPT-FAILED"
ERR_LIFECYCLE_RELAY_SHUTDOWN_FAILED = "ERR-LIFECYCLE-RELAY-SHUTDOWN-FAILED"

# ── Comms errors ──

ERR_COMMS_RELAY_CHECK_FAILED = "ERR-COMMS-RELAY-CHECK-FAILED"
ERR_COMMS_URL_TO_BASE64_FAILED = "ERR-COMMS-URL-TO-BASE64-FAILED"
ERR_COMMS_DASHBOARD_PUSH_FAILED = "ERR-COMMS-DASHBOARD-PUSH-FAILED"
ERR_COMMS_THEME_PUSH_FAILED = "ERR-COMMS-THEME-PUSH-FAILED"
ERR_COMMS_SKILL_PUSH_FAILED = "ERR-COMMS-SKILL-PUSH-FAILED"
ERR_COMMS_SKILL_CLEANUP_FAILED = "ERR-COMMS-SKILL-CLEANUP-FAILED"
ERR_COMMS_SESSION_CLEANUP_FAILED = "ERR-COMMS-SESSION-CLEANUP-FAILED"
ERR_COMMS_INPUT_NON_DURABLE = "ERR-COMMS-INPUT-NON-DURABLE-PATH"

# ── Broadcast errors ──

ERR_BROADCAST_DASHBOARD_PUSH_FAILED = "ERR-BROADCAST-DASHBOARD-PUSH-FAILED"

# ── Feed errors ──

ERR_FEED_DASHBOARD_PUSH_FAILED = "ERR-FEED-DASHBOARD-PUSH-FAILED"

# ── Consumer errors ──

ERR_CONSUMER_RELAY_UPDATE_FAILED = "ERR-CONSUMER-RELAY-UPDATE-FAILED"
ERR_CONSUMER_CALLBACK_FAILED = "ERR-CONSUMER-CALLBACK-FAILED"
ERR_CONSUMER_EVENT_FAILED = "ERR-CONSUMER-EVENT-FAILED"
ERR_CONSUMER_VNC_UPSTREAM_FAILED = "ERR-CONSUMER-VNC-UPSTREAM-FAILED"
ERR_CONSUMER_VNC_UPSTREAM_CLOSED = "ERR-CONSUMER-VNC-UPSTREAM-CLOSED"
ERR_CONSUMER_VNC_SEND_FAILED = "ERR-CONSUMER-VNC-SEND-FAILED"
ERR_CONSUMER_VNC_CLOSE_FAILED = "ERR-CONSUMER-VNC-CLOSE-FAILED"

# ── Reconciler errors ──

ERR_RECONCILER_LOOP_FAILED = "ERR-RECONCILER-LOOP-FAILED"
ERR_RECONCILER_STATUS_CHECK_FAILED = "ERR-RECONCILER-STATUS-CHECK-FAILED"

# ── Media errors ──

ERR_MEDIA_EXTERNALIZE_FAILED = "ERR-MEDIA-EXTERNALIZE-FAILED"

# ── Utils errors ──

ERR_UTILS_TERMINATE_FAILED = "ERR-UTILS-TERMINATE-FAILED"
ERR_UTILS_BACKGROUND_TASK_FAILED = "ERR-UTILS-BACKGROUND-TASK-FAILED"

# ── Secrets errors ──

ERR_SECRETS_PUSH_FAILED = "ERR-SECRETS-PUSH-FAILED"

# ── MCP coordination errors ──

ERR_MCP_FEED_ITEM_FAILED = "ERR-MCP-FEED-ITEM-FAILED"
ERR_MCP_BROADCAST_FAILED = "ERR-MCP-BROADCAST-FAILED"

# ── Observability errors ──

ERR_OBS_METADATA_MISSING = "ERR-OBS-METADATA-MISSING"

# ── Dependency errors ──

ERR_DEPENDENCY_COMPATIBILITY = "ERR-DEPENDENCY-COMPATIBILITY"

# ── Incident capture errors ──

ERR_INCIDENT_SOURCE_FAILED = "ERR-INCIDENT-SOURCE-FAILED"

# ── Runtime errors ──

ERR_RUNTIME_TAG_FAILED = "ERR-RUNTIME-TAG-FAILED"
