# Generated by Django 6.0.3 on 2026-04-01 01:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0003_project_theme_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCommitment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("commitment_id", models.CharField(max_length=255)),
                ("objective_id", models.CharField(max_length=255)),
                ("capability_id", models.CharField(max_length=255)),
                ("arguments", models.JSONField(blank=True, default=dict)),
                ("touched_scope", models.JSONField(blank=True, default=list)),
                ("status", models.CharField(default="proposed", max_length=32)),
                ("expected_observation", models.JSONField(blank=True, default=dict)),
                ("expected_outcome", models.JSONField(blank=True, default=dict)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("close_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gda_commitments",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("invocation_id", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=32)),
                ("resource_usage", models.JSONField(blank=True, default=dict)),
                ("artifact_refs", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "commitment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executions",
                        to="gda.projectcommitment",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gda_executions",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectObservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("observation_id", models.CharField(max_length=255)),
                ("kind", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("observed_at", models.DateTimeField()),
                ("valid_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("source_kind", models.CharField(max_length=128)),
                ("source_id", models.CharField(max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("provenance_refs", models.JSONField(blank=True, default=list)),
                ("quality", models.CharField(default="exact", max_length=32)),
                ("admitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gda_observations",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["observed_at", "admitted_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("world_ref", models.CharField(blank=True, default="", max_length=255)),
                ("run_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "evaluator_profile",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("status", models.CharField(default="idle", max_length=32)),
                ("subject", models.CharField(blank=True, default="", max_length=255)),
                ("state_version_id", models.CharField(default="v1", max_length=64)),
                ("observed_at", models.DateTimeField(blank=True, null=True)),
                ("source_refs", models.JSONField(blank=True, default=list)),
                ("facts", models.JSONField(blank=True, default=dict)),
                ("objective", models.JSONField(blank=True, default=dict)),
                ("boundary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gda_state",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="projectcommitment",
            constraint=models.UniqueConstraint(
                fields=("project", "commitment_id"), name="unique_project_commitment_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectexecution",
            constraint=models.UniqueConstraint(
                fields=("project", "invocation_id"), name="unique_project_invocation_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectobservation",
            constraint=models.UniqueConstraint(
                fields=("project", "observation_id"),
                name="unique_project_observation_id",
            ),
        ),
    ]
