# Generated by Django 6.0.3 on 2026-04-02 17:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gda", "0001_initial"),
        ("projects", "0003_project_theme_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectStateEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("dimension_id", models.CharField(max_length=255)),
                ("schema_ref", models.CharField(max_length=255)),
                ("origin", models.CharField(max_length=32)),
                ("value", models.JSONField(blank=True, default=dict)),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("provenance_refs", models.JSONField(blank=True, default=list)),
                ("state_version_id", models.CharField(default="v1", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gda_state_entries",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["dimension_id", "-updated_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "dimension_id"),
                        name="unique_project_state_entry_dimension",
                    )
                ],
            },
        ),
    ]
