# Generated by Django 6.0.3 on 2026-04-02 21:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0011_incident_capture_set_null_fks"),
        ("gda", "0002_projectstateentry"),
        ("projects", "0003_project_theme_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCommitmentAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("dimension_ids", models.JSONField(blank=True, default=list)),
                ("observation_kinds", models.JSONField(blank=True, default=list)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gda_commitment_assignments",
                        to="agents.agent",
                    ),
                ),
                (
                    "commitment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment",
                        to="gda.projectcommitment",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gda_commitment_assignments",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-assigned_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "commitment", "agent"),
                        name="unique_project_commitment_assignment",
                    )
                ],
            },
        ),
    ]
