import Link from "next/link"
import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Privacy Policy — Agentobox",
  description: "Agentobox privacy policy",
}

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-surface">
      <div className="mx-auto max-w-2xl px-6 py-16">
        <Link
          href="/login"
          className="inline-flex items-center gap-1.5 text-[13px] text-text-link hover:text-text-link-hover transition-colors mb-10"
        >
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <path d="M19 12H5M12 19l-7-7 7-7" />
          </svg>
          Back to login
        </Link>

        <h1 className="text-2xl font-semibold text-default tracking-tight mb-2">Privacy Policy</h1>
        <p className="text-[13px] text-muted mb-12">Last updated: March 2026</p>

        <div className="space-y-10 text-[14px] text-secondary leading-relaxed">
          <section>
            <h2 className="text-[15px] font-medium text-default mb-3">1. Information We Collect</h2>
            <p className="mb-3">We collect the following types of information when you use Agentobox:</p>
            <ul className="list-disc pl-5 space-y-1.5 text-secondary/90">
              <li><span className="text-default font-medium">Account information</span> — email address, name, and profile data from your OAuth provider (Google or GitHub)</li>
              <li><span className="text-default font-medium">Usage data</span> — agent configurations, workflow history, dashboard interactions, and feature usage patterns</li>
              <li><span className="text-default font-medium">Agent logs</span> — operational logs generated by your AI agents during execution</li>
              <li><span className="text-default font-medium">Technical data</span> — browser type, IP address, device information, and access timestamps</li>
            </ul>
          </section>

          <section>
            <h2 className="text-[15px] font-medium text-default mb-3">2. How We Use Your Information</h2>
            <ul className="list-disc pl-5 space-y-1.5 text-secondary/90">
              <li>Provide, operate, and maintain the Service</li>
              <li>Authenticate your identity and manage your account</li>
              <li>Improve the Service based on usage patterns and feedback</li>
              <li>Respond to support requests and communicate service updates</li>
              <li>Detect, prevent, and address technical issues or abuse</li>
            </ul>
          </section>

          <section>
            <h2 className="text-[15px] font-medium text-default mb-3">3. What We Do Not Do</h2>
            <ul className="list-disc pl-5 space-y-1.5 text-secondary/90">
              <li>We do not sell your personal data to third parties</li>
              <li>We do not share your data with third parties for marketing purposes</li>
              <li>We do not use your workspace content or agent outputs to train AI models</li>
              <li>We do not access your workspace data except as necessary to operate the Service</li>
            </ul>
          </section>

          <section>
            <h2 className="text-[15px] font-medium text-default mb-3">4. API Keys (BYOK)</h2>
            <p>
              When you provide API keys for third-party AI providers, we encrypt them at rest and use
              them solely to authenticate requests on your behalf. Your API keys are never shared with
              other users or third parties. You can delete your stored API keys at any time through
              the dashboard, and they will be permanently removed from our systems.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-medium text-default mb-3">5. Workspace Data</h2>
            <p>
              Your workspace data — including code, files, and agent outputs — belongs to you. We do not
              access, review, or analyze your workspace content except as required to provide the Service
              (e.g., mounting workspaces to agent containers). Workspace data is isolated per user and
              is not shared across accounts.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-medium text-default mb-3">6. Cookies and Authentication</h2>
            <p>
              We use session cookies and authentication tokens to maintain your logged-in state and
              secure your account. These are essential for the Service to function and cannot be
              disabled. We do not use tracking cookies or third-party advertising cookies.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-medium text-default mb-3">7. Data Retention</h2>
            <p>
              We retain your account data for as long as your account is active. Agent logs and
              execution history are retained for 90 days by default, after which they are automatically
              deleted. When you delete your account, all associated data is permanently removed
              within 30 days.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-medium text-default mb-3">8. Your Rights</h2>
            <p className="mb-2">You have the right to:</p>
            <ul className="list-disc pl-5 space-y-1.5 text-secondary/90">
              <li><span className="text-default font-medium">Access</span> — request a copy of your personal data</li>
              <li><span className="text-default font-medium">Deletion</span> — request deletion of your account and all associated data</li>
              <li><span className="text-default font-medium">Export</span> — export your data in a portable format</li>
              <li><span className="text-default font-medium">Correction</span> — update or correct inaccurate personal information</li>
            </ul>
            <p className="mt-3">
              To exercise any of these rights, contact us at{" "}
              <a href="mailto:support@agentobox.com" className="text-text-link hover:text-text-link-hover underline decoration-text-link/30 hover:decoration-text-link/60 transition-colors">
                support@agentobox.com
              </a>
              .
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-medium text-default mb-3">9. Third-Party Services</h2>
            <p>
              The Service integrates with third-party services for authentication (Google, GitHub) and
              infrastructure hosting. These providers have their own privacy policies governing their
              handling of your data. We share only the minimum information necessary for these
              integrations to function.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-medium text-default mb-3">10. Security</h2>
            <p>
              We implement industry-standard security measures to protect your data, including encryption
              in transit (TLS), encryption at rest for sensitive data like API keys, isolated container
              environments per agent, and access controls. However, no method of transmission or storage
              is completely secure, and we cannot guarantee absolute security.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-medium text-default mb-3">11. Changes to This Policy</h2>
            <p>
              We may update this privacy policy from time to time. Material changes will be communicated
              through the Service or via email. Your continued use of the Service after changes take
              effect constitutes acceptance of the updated policy.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-medium text-default mb-3">12. Contact</h2>
            <p>
              If you have questions about this privacy policy or our data practices, contact us at{" "}
              <a href="mailto:support@agentobox.com" className="text-text-link hover:text-text-link-hover underline decoration-text-link/30 hover:decoration-text-link/60 transition-colors">
                support@agentobox.com
              </a>
              .
            </p>
          </section>
        </div>
      </div>
    </div>
  )
}
